-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "DB1".groom
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    age integer NOT NULL,
    order_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "DB1"."wedding organizer"
(
    id integer NOT NULL,
    "social credit" integer NOT NULL,
    name character varying(30) NOT NULL,
    organizer_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "DB1"."order"
(
    id integer NOT NULL,
    "groom`s id" integer NOT NULL,
    wedding date NOT NULL,
    "number of guests" integer NOT NULL,
    payment integer NOT NULL,
    location character varying(100) NOT NULL,
    services character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "DB1"."detail order"
(
    id integer NOT NULL,
    musicians character varying(3) NOT NULL,
    "video recording" character varying(3) NOT NULL,
    toastmaster character varying(3) NOT NULL,
    chef character varying(3) NOT NULL,
    choreographer character varying(3) NOT NULL,
    detail_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "DB1".groom
    ADD FOREIGN KEY (order_id)
    REFERENCES "DB1"."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB1"."wedding organizer"
    ADD FOREIGN KEY (organizer_id)
    REFERENCES "DB1"."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "DB1"."detail order"
    ADD FOREIGN KEY (detail_id)
    REFERENCES "DB1"."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;